# Capture and recording
# Screenshots, recordings and OCR.

### Screenshots
bindsym Print exec ~/.config/sway/scripts/screenshot-area
bindsym $mod+Print exec ~/.config/sway/scripts/screenshot-thinkpad
bindsym $mod+Shift+Print exec ~/.config/sway/scripts/screenshot-asus

### Screenshot to clipboard
bindsym $mod+Ctrl+Print exec ~/.config/sway/scripts/screenshot-area-clipboard

### Screen recording
bindsym $mod+Ctrl+1 exec ~/.config/sway/scripts/sway-record 1
bindsym $mod+Ctrl+2 exec ~/.config/sway/scripts/sway-record 2
bindsym $mod+Ctrl+3 exec ~/.config/sway/scripts/sway-record 3

### Camera recording
bindsym $mod+Ctrl+4 exec ~/.config/sway/scripts/sway-camera-record

### Screen and camera recording
bindsym $mod+Ctrl+5 exec ~/.config/sway/scripts/sway-screen-camera-record

### OCR
bindsym $mod+Ctrl+Shift+Print exec "$HOME/.config/sway/scripts/sway-ocr"
