# Input configuration

seat seat0 xcursor_theme Adwaita 24

# Keyboard layouts
input "type:keyboard" {
    xkb_layout "us,tr"
}

# Toggle keyboard layout
bindsym $mod+Ctrl+space exec ~/.config/sway/scripts/input/keyboard-layout-toggle

# Keyboard-driven window focus
focus_follows_mouse no

# Move pointer when focus changes between outputs
mouse_warping output
