# Output configuration

# Global wallpaper
output * bg /home/murat/.wallpapers/sam-ferrara-uNvgvo2cs7k-unsplash.jpg fill

# ThinkPad E490 internal display
output eDP-1 {
    scale 1
    subpixel rgb
}

# ASUS VN247 external display
output HDMI-A-1 {
    scale 1
    subpixel rgb
}
