# Application and utility shortcuts
# Launchers, terminals, applications and user tools.

### Launcher
bindsym $mod+d exec $menu

### Clipboard history
bindsym $mod+Shift+v exec ~/.config/sway/scripts/clipboard-history

### File managers
bindsym $mod+y exec /usr/local/bin/kitty ~/.local/bin/yazi

### Terminals
bindsym $mod+Ctrl+Return exec alacritty

### Applications
bindsym $mod+F10 exec /usr/local/bin/snapshot
bindsym $mod+p exec /usr/local/bin/flameshot gui

### Display modes
bindsym $mod+Shift+a exec ~/.config/sway/scripts/display-mode.sh asus
bindsym $mod+Shift+t exec ~/.config/sway/scripts/display-mode.sh thinkpad
bindsym $mod+Shift+d exec ~/.config/sway/scripts/display-mode.sh dual

### Voice typing
bindsym $mod+i exec $HOME/.local/bin/whisper-type.sh
bindsym $mod+Shift+i exec $HOME/.local/bin/whisper-type.sh en

### Sway help
bindsym $mod+F11 exec /usr/local/bin/foot /usr/local/bin/glow -p ~/.config/sway/docs/README.md

### Wayland color picker
bindsym $mod+Ctrl+p exec /usr/bin/wl-color-picker

### Notification history
bindsym $mod+Ctrl+n exec ~/.config/sway/scripts/notification-history

# Emoji picker
bindsym $mod+Ctrl+e exec ~/.config/sway/scripts/emoji-picker
