#!/usr/bin/env bash

"$HOME/.config/sway/scripts/sway-shortcuts" --print |
awk -F '\t' '
BEGIN {
    printf "%-28s │ %s\n", "SHORTCUT", "DESCRIPTION"
    printf "%-28s─┼─%s\n", "────────────────────────────", "────────────────────────────────────────"
}
{
    printf "%-28s │ %s\n", $1, $2
}
' | less -R -S
