---
- name: Check chezmoi installation
  ansible.builtin.command:
    cmd: chezmoi --version
  register: chezmoi_version
  changed_when: false

- name: Show chezmoi version
  ansible.builtin.debug:
    var: chezmoi_version.stdout
