#!/usr/bin/env bash
set -euo pipefail

swaymsg input "type:keyboard" xkb_switch_layout next >/dev/null

sleep 0.05

layout="$(
    swaymsg -t get_inputs |
    jq -r '
        .[]
        | select(.type == "keyboard")
        | .xkb_active_layout_name
    ' |
    head -n1
)"

case "$layout" in
    "English (US)")
        notify-send -a "Sway" -r 9911 "Keyboard Layout" "󰌌 EN"
        ;;
    "Turkish")
        notify-send -a "Sway" -r 9911 "Keyboard Layout" "󰌌 TR"
        ;;
    *)
        notify-send -a "Sway" -r 9911 "Keyboard Layout" "$layout"
        ;;
esac
