# ==============================================================================
# CUSTOM REGEX
# ==============================================================================
#
# Custom regular expressions use named sections:
#
# [regex:name]
#
# Each custom regex can define:
# - regex  = POSIX Extended Regular Expression used for matching text
# - launch = command executed when launching the matched text
#
# ${match} is replaced with the matched text.
#
# The first marked subexpression is used as the match.
# To use the complete regular expression match, wrap the whole pattern in
# parentheses.
#
# A custom regex also requires corresponding bindings in [key-bindings],
# using regex-launch and/or regex-copy.
#
# Example:
#
# [regex:hashes]
# regex=([a-fA-F0-9]{7,128})
# launch=path-to-script-or-application ${match}
#
# Defaults:
# regex  = not set
# launch = not set
