#!/usr/bin/env bash

CARD_ID=$(wpctl status -n | grep alsa_card | awk '{print $2}' | tr -d '.')

case "$1" in
    asus)
        wpctl set-profile "$CARD_ID" 4
        ;;
    thinkpad)
        wpctl set-profile "$CARD_ID" 1
        ;;
esac
