#!/usr/bin/env bash
set -euo pipefail

STATE_FILE="$HOME/.cache/mako-popup-state"

if makoctl mode | grep -q "do-not-disturb"; then
    makoctl mode -r do-not-disturb
    echo enabled > "$STATE_FILE"
else
    makoctl mode -a do-not-disturb
    echo disabled > "$STATE_FILE"
fi
